### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by Heufneutje** [Heufneutje/WinWeelay#1]
### Remaining WeeChat signals
- [x] _buffer_opened
- [x] _buffer_moved
- [x] _buffer_hidden
- [x] _buffer_unhidden
- [x] _buffer_renamed
- [x] _buffer_title_changed
- [x] _buffer_cleared
- [x] _buffer_line_added
- [x] _buffer_closing
- [x] _nicklist
- [x] _nicklist_diff
- [x] _pong
- [x] _upgrade
- [x] _upgrade_ended

### Must-have
- [x] Syncing read messages with host
- [x] Arrow key navigation through old messages
- [x] IRC color parsing
- [x] Automatically reconnect when connection drops (ping?)
- [x] Secure connections
- [x] Nick colors
- [x] Loading messages that are older than the initial backlog
- [x] Remember dock layout
- [x] Proper validation on connection settings
- [x] Display hotlist items
- [x] Notifications when highlighted
- [x] Investigate nicks sometimes appearing in the nicklist twice
- [x] Send commands in batches where applicable 
- [x] Fix notifications only sending when the buffer is active
- [x] Make URLs clickable
- [x] Investigate why selecting all text in the input box and hitting backspace only deletes the last character

### Nice-to-have
- [x] Theme support
- [x] Synchronizing nick colors with host
- [x] Parse colors specified by the host's options

**Comment by Heufneutje** [comment]
That should be it for all the features!
